CREATE TABLE [SMARTDEV_HOTEL_APP].[Booking](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoomId] [int] NULL,
	[GuestId] [int] NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[CheckedIn] [bit] NULL,
	[TotalCost] [money] NULL,
	[CreatedOn] [datetime] NULL,
 CONSTRAINT [PK_Booking] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SMARTDEV_HOTEL_APP].[Booking] ADD  CONSTRAINT [DF_Booking_CreatedOn]  DEFAULT (getdate()) FOR [CreatedOn]
GO

ALTER TABLE [SMARTDEV_HOTEL_APP].[Booking]  WITH CHECK ADD  CONSTRAINT [FK_Booking_Guest] FOREIGN KEY([GuestId])
REFERENCES [SMARTDEV_HOTEL_APP].[Guest] ([Id])
GO

ALTER TABLE [SMARTDEV_HOTEL_APP].[Booking] CHECK CONSTRAINT [FK_Booking_Guest]
GO

ALTER TABLE [SMARTDEV_HOTEL_APP].[Booking]  WITH CHECK ADD  CONSTRAINT [FK_Booking_Room] FOREIGN KEY([RoomId])
REFERENCES [SMARTDEV_HOTEL_APP].[Room] ([Id])
GO

ALTER TABLE [SMARTDEV_HOTEL_APP].[Booking] CHECK CONSTRAINT [FK_Booking_Room]
GO
