CREATE TABLE [SMARTDEV_HOTEL_APP].[Room](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoomNumber] [nvarchar](10) NULL,
	[RoomTypeId] [int] NULL,
	[CreatedOn] [datetime] NULL,
 CONSTRAINT [PK_Room] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SMARTDEV_HOTEL_APP].[Room] ADD  CONSTRAINT [DF_Room_CreatedOn]  DEFAULT (getdate()) FOR [CreatedOn]
GO

ALTER TABLE [SMARTDEV_HOTEL_APP].[Room]  WITH CHECK ADD  CONSTRAINT [FK_Room_RoomType] FOREIGN KEY([RoomTypeId])
REFERENCES [SMARTDEV_HOTEL_APP].[RoomType] ([Id])
GO

ALTER TABLE [SMARTDEV_HOTEL_APP].[Room] CHECK CONSTRAINT [FK_Room_RoomType]
GO
